version: "3.5"

services:
    web:
        container_name: web
        build: .
        restart: always
        networks:
            - proxynet
        environment:
            - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        #command: >
        #    bash -c "python manage.py makemigrations
        #    && python manage.py migrate
        #    && python manage.py createsuperuser --no-input --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL}
        #    && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 10555:8000
        #depends_on:
        #    - db
    
networks:
    proxynet:
        name: apps-net
    #default:
    #    external: true
    #        name: apps-net


